### ISSUE TITLE
Warning when using onlyNew

### ISSUE THREAD

**Issue by samsmithnz** [tspascoal/whack-a-branch#8]
Now sure why, but when using onlyNew, it posts a warning:

`Warning: Unexpected input(s) 'onlyNew', valid inputs are ['token', 'branches-keep', 'branches-delete', 'delete-if-no-match', 'dry-run', 'output-separator']`

Seems to still work, but is odd. 

![image](https://user-images.githubusercontent.com/8389039/151601792-4f5c2164-40e5-4ca9-b24a-0fa76fc3b246.png)

Here is the source I'm using
```
      - uses: tspascoal/whack-a-branch@v1 
        id: deletebranches
        with:
          branches-keep: 'main,develop,features/*,releases/*'
          onlyNew: true
          delete-if-no-match: true
          dry-run: false
```
